In [ ]:
#From Scratch NumPy

In [ ]:
#Import NumPy library

In [6]:
from numpy import *

In [7]:
a = array([2,3,4])
print(a);

[2 3 4]


In [8]:
a.ndim #this will show us array dimensions (could be one-dimensional, two-dimensional and etc)

1

In [10]:
a.shape #this gonna show us array sizes  (# of rows, # of columns)

(3,)

In [14]:
b = array([(2,3,4), (5,6,7)]) #creating two-dimensional array
print(b);

[[2 3 4]
 [5 6 7]]


In [15]:
b.ndim #B is already two-dimensional

2

In [17]:
b.shape  #B have right now 2 rows and 3 columns

(2, 3)

In [20]:
z = zeros((5,5)) #generate Z variable with 5 zeroes in a row and columns
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
arange(10,30,5) #arange func is similar to range, but returns an array. 10 - first number, 30 - last number and 5 by steps

array([10, 15, 20, 25])

In [25]:
linspace(1,12,8) #generates 8 numbers from 1 to 12 number

array([ 1.        ,  2.57142857,  4.14285714,  5.71428571,  7.28571429,
        8.85714286, 10.42857143, 12.        ])